name: React CI/CD

on:
  push:
    branch: [deploy]

jobs:
  build:
    runs-on: self-hosted 

    strategy:
    matrix:
     node-version: [18.x]


    steps:
    - name: Checkout
      - uses: actions/checkout@v2

    - name: Setup node
      - uses: actions/setup-node@v2
        with:
        node-version: ${{matrix.node-version}}

      - run: npm ci
      - run: npm test


      - name: Install dependencies
        run: npm install

      - name: test file
        run: npm test

     - name: Build static file
       run: npm run build
     
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

    #       name: s3-depl

# jobs:
#  Deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2

#      - name: Setup node
#        uses: actions/setup-node@v2

#      - name: Install dependencies
#        run: npm install

#      - name: Build static file
#        run: npm run build

