name: React CI/CD

on:
  push:
    branches : [deploy]

jobs:
  build:
    runs-on: self-hosted 

    strategy:
    matrix:
     node-version: [18.x]


    jobs:
   Deploy:
   runs-on: ubuntu-latest


    steps:
     - name: Checkout
       uses: actions/checkout@v2

     - name: Setup node
       uses: actions/setup-node@v2

     - name: Install dependencies
       run: npm install

     - name: Build static file
       run: npm run build
     


