name: React CI/CD

on:
  push:
    branches : [deploy]

jobs:
  build:
    runs-on: self-hosted 

    strategy:
    matrix:
     node-version: [18.x]


    steps:
    - name: Checkout
      - uses: actions/checkout@v2

    - name: Setup node
      - uses: actions/setup-node@v2
        with:
        node-version: ${{matrix.node-version}}

      - name: Install dependencies
        run: npm install

      - name: test file
        run: npm test

     - name: Build static file
       run: npm run build
     


